### PR TITLE
Filter API calls based on network type.

### PR DESCRIPTION
**Pull request by phdonnelly**
Check network productTypes field before calling API functions that depend on that product being present.

### CODE REVIEW

**Review by JustOneMoreDog — COMMENTED** [review]
I modified the code a little so as to include else statements with your if statements. This way the progress bar gets updated even if the api calls are not made. Also, can you confirm this code worked for you? I am mainly concerned about the clients section. It calls an auxiliary function and does the api call there. I am not sure if you MDM network has that api endpoint or not

**Comment by JustOneMoreDog** [comment]
[MTA.txt](https://github.com/picnicsecurity/Meraki-Traffic-Analyzer/files/5586085/MTA.txt)

someday ill learn how to use git

**Comment by phdonnelly** [comment]
Perfect; works and displays the progress bar properly as well now.

The client code does work for the MDM network; I think it pulls the
enrolled devices as "clients"

*Patrick Donnelly*

**Comment by JustOneMoreDog** [comment]
So I did some testing on my end and found a couple more things that needed to be fixed. 
I will add them to the commit. Once you confirm everything still works for you ill merge this to master

**Pull request merged**
